#FROM tutum/nginx
FROM ubuntu:14.04 
RUN apt-get update
RUN apt-get install nginx curl -y
COPY ./confddir/confd /usr/local/bin/
RUN chmod +x /usr/local/bin/confd
RUN rm /etc/nginx/sites-enabled/default
#ADD sites-enabled /etc/nginx/sites-enabled
